#
# Module manifest for module 'GoogleCloudPowerShell'
#
# This is a hack to keep existing Cloud SDK installs working after renaming the
# module to GoogleCloud. See the comment in Tools\BuildAndPackage.ps1 for more
# information.
#
# Generated by: Google Inc
#
# Generated on: 11/7/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '..\PowerShell\GoogleCloud\Google.PowerShell.dll'

# Version number of this module.
ModuleVersion = '0.1.10.0'

# ID used to uniquely identify this module
GUID = 'e74637e6-7a4e-422d-bb9c-ca50809d78bb'

# Author of this module
Author = 'Google Inc'

# Company or vendor of this module
CompanyName = 'Google Inc'

# Copyright statement for this module
Copyright = 'Google Inc. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell cmdlets for the Google Cloud Platform.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = '..\PowerShell\GoogleCloud\GoogleCloudPlatform.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module
# FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @('Add-GcdChange', 'Add-GcdManagedZone', 'Add-GceAddress',
               'Add-GceFirewall', 'Add-GceHealthCheck', 'Add-GceImage',
               'Add-GceInstance', 'Add-GceInstanceTemplate',
               'Add-GceManagedInstanceGroup', 'Add-GceRoute', 'Add-GceSnapshot',
               'Add-GcSqlInstance', 'Add-GcSqlSslCert', 'Add-GcSqlSslEphemeral',
               'ConvertTo-GcSqlInstance', 'Copy-GcsObject', 'Disable-GceImage',
               'Export-GcSqlInstance', 'Find-GcsObject', 'Get-GcdChange',
               'Get-GcdManagedZone', 'Get-GcdQuota', 'Get-GcdResourceRecordSet',
               'Get-GceAddress', 'Get-GceBackendService', 'Get-GceDisk',
               'Get-GceFirewall', 'Get-GceForwardingRule', 'Get-GceHealthCheck',
               'Get-GceImage', 'Get-GceInstance', 'Get-GceInstanceTemplate',
               'Get-GceMachineType', 'Get-GceManagedInstanceGroup',
               'Get-GceMetadata', 'Get-GceNetwork', 'Get-GceRoute', 'Get-GceSnapshot',
               'Get-GceTargetPool', 'Get-GceTargetProxy', 'Get-GceUrlMap',
               'Get-GcsBucket', 'Get-GcsObject', 'Get-GcSqlBackupRun',
               'Get-GcSqlFlags', 'Get-GcSqlInstance', 'Get-GcSqlOperation',
               'Get-GcSqlSslCert', 'Get-GcSqlTiers', 'Import-GcSqlInstance',
               'Invoke-GcSqlInstanceFailover', 'New-GcdResourceRecordSet',
               'New-GceAttachedDiskConfig', 'New-GceDisk', 'New-GceFirewallProtocol',
               'New-GceInstanceConfig', 'New-GceServiceAccountConfig',
               'New-GcsBucket', 'New-GcsObject', 'New-GcSqlInstanceConfig',
               'New-GcSqlInstanceReplicaConfig', 'New-GcSqlSettingConfig',
               'Read-GcsObject', 'Remove-GcdManagedZone', 'Remove-GceAddress',
               'Remove-GceDisk', 'Remove-GceFirewall', 'Remove-GceHealthCheck',
               'Remove-GceImage', 'Remove-GceInstance', 'Remove-GceInstanceTemplate',
               'Remove-GceManagedInstanceGroup', 'Remove-GceRoute',
               'Remove-GceSnapshot', 'Remove-GcsBucket', 'Remove-GcsBucketLogging',
               'Remove-GcsBucketWebsite', 'Remove-GcsObject',
               'Remove-GcSqlBackupRun', 'Remove-GcSqlInstance',
               'Remove-GcSqlSslCert', 'Reset-GcSqlSslConfig', 'Resize-GceDisk',
               'Restart-GceInstance', 'Restart-GcSqlInstance',
               'Restore-GcSqlInstanceBackup', 'Set-GceFirewall',
               'Set-GceHealthCheck', 'Set-GceInstance',
               'Set-GceManagedInstanceGroup', 'Set-GceTargetPool', 'Set-GcsObject',
               'Start-GceInstance', 'Start-GcSqlReplica', 'Stop-GceInstance',
               'Stop-GcSqlReplica', 'Test-GcsBucket', 'Test-GcsObject',
               'Update-GcSqlInstance', 'Wait-GceManagedInstanceGroup',
               'Write-GcsBucketLogging', 'Write-GcsBucketWebsite', 'Write-GcsObject')

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module
# AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

