#
# Module manifest for module 'GoogleCloudPowerShell'
#
# Generated by: Google Inc
#
# Generated on: 12/17/2015
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.1.0'

# ID used to uniquely identify this module
GUID = 'e74637e6-7a4e-422d-bb9c-ca50809d78bb'

# Author of this module
Author = 'Google Inc'

# Company or vendor of this module
CompanyName = 'Google Inc'

# Copyright statement for this module
Copyright = 'Google Inc. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell cmdlets for the Google Cloud Platform.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @("GoogleCloudPlatform.Format.ps1xml")

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('.\Google.PowerShell.dll')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = 'Add-GcdChange', 'Get-GcdChange', 'Add-GcdManagedZone', 'Get-GcdManagedZone',
    'Remove-GcdManagedZone', 'Get-GcdQuota', 'Get-GcdResourceRecordSet', 'New-GcdResourceRecordSet',
    'Add-GceAddress', 'Get-GceAddress', 'Remove-GceAddress', 'New-GceAttachedDiskConfig',
    'Get-GceBackendService', 'Get-GceDisk', 'New-GceDisk', 'Remove-GceDisk', 'Resize-GceDisk',
    'Add-GceFirewall', 'Get-GceFirewall', 'Remove-GceFirewall', 'Set-GceFirewall', 'New-GceFirewallProtocol',
    'Get-GceForwardingRule', 'Add-GceHealthCheck', 'Get-GceHealthCheck', 'Remove-GceHealthCheck',
    'Set-GceHealthCheck', 'Add-GceImage', 'Disable-GceImage', 'Get-GceImage', 'Remove-GceImage',
    'Add-GceInstance', 'Get-GceInstance', 'Remove-GceInstance', 'Restart-GceInstance', 'Set-GceInstance',
    'Start-GceInstance', 'Stop-GceInstance', 'New-GceInstanceConfig', 'Add-GceInstanceTemplate',
    'Get-GceInstanceTemplate', 'Remove-GceInstanceTemplate', 'Get-GceMachineType',
    'Add-GceManagedInstanceGroup', 'Get-GceManagedInstanceGroup', 'Remove-GceManagedInstanceGroup',
    'Set-GceManagedInstanceGroup', 'Wait-GceManagedInstanceGroup', 'Get-GceMetadata', 'Get-GceNetwork',
     'Add-GceRoute', 'Get-GceRoute', 'Remove-GceRoute', 'New-GceServiceAccountConfig', 'Add-GceSnapshot',
    'Get-GceSnapshot', 'Remove-GceSnapshot', 'Get-GceTargetPool', 'Set-GceTargetPool', 'Get-GceTargetProxy',
    'Get-GceUrlMap', 'Get-GcsBucket', 'New-GcsBucket', 'Remove-GcsBucket', 'Test-GcsBucket',
    'Remove-GcsBucketLogging', 'Write-GcsBucketLogging', 'Remove-GcsBucketWebsite', 'Write-GcsBucketWebsite',
    'Copy-GcsObject', 'Find-GcsObject', 'Get-GcsObject', 'New-GcsObject', 'Read-GcsObject', 'Remove-GcsObject',
    'Set-GcsObject', 'Test-GcsObject', 'Write-GcsObject', 'Get-GcSqlBackupRun', 'Remove-GcSqlBackupRun',
    'Get-GcSqlFlags', 'Add-GcSqlInstance', 'Export-GcSqlInstance', 'Invoke-GcSqlInstanceFailover',
    'Get-GcSqlInstance', 'Import-GcSqlInstance', 'Remove-GcSqlInstance', 'Restart-GcSqlInstance',
    'Update-GcSqlInstance', 'Restore-GcSqlInstanceBackup', 'New-GcSqlInstanceConfig',
    'New-GcSqlInstanceReplicaConfig', 'Get-GcSqlOperation', 'Convert-GcSqlReplicaToInstance', 'Start-GcSqlReplica',
    'Stop-GcSqlReplica', 'New-GcSqlSettingConfig', 'Add-GcSqlSslCert', 'Get-GcSqlSslCert',
    'Remove-GcSqlSslCert', 'Reset-GcSqlSslConfig', 'Add-GcSqlSslEphemeral', 'Get-GcSqlTiers'

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
